--- #YAML:1.0
name:                Data-YAML
version:             0.0.3
abstract:            Easy YAML serialisation of Perl data structures
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
